-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 24, 2024 at 10:55 AM
-- Server version: 5.7.44
-- PHP Version: 8.1.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `niifslkj_easse_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE `questions` (
  `id` bigint(255) NOT NULL,
  `term` varchar(200) NOT NULL,
  `session` varchar(200) NOT NULL,
  `type` varchar(200) NOT NULL,
  `class` varchar(200) NOT NULL,
  `subject` varchar(200) NOT NULL,
  `instruction` text NOT NULL,
  `q1` varchar(255) NOT NULL,
  `q1_opt_a` varchar(255) NOT NULL,
  `q1_opt_b` varchar(255) NOT NULL,
  `q1_opt_c` varchar(255) NOT NULL,
  `q1_opt_d` varchar(255) NOT NULL,
  `q1_answer` varchar(255) NOT NULL,
  `q2` varchar(255) NOT NULL,
  `q2_opt_a` varchar(255) NOT NULL,
  `q2_opt_b` varchar(255) NOT NULL,
  `q2_opt_c` varchar(255) NOT NULL,
  `q2_opt_d` varchar(255) NOT NULL,
  `q2_answer` varchar(255) NOT NULL,
  `q3` varchar(255) NOT NULL,
  `q3_opt_a` varchar(255) NOT NULL,
  `q3_opt_b` varchar(255) NOT NULL,
  `q3_opt_c` varchar(255) NOT NULL,
  `q3_opt_d` varchar(255) NOT NULL,
  `q3_answer` varchar(255) NOT NULL,
  `q4` varchar(255) NOT NULL,
  `q4_opt_a` varchar(255) NOT NULL,
  `q4_opt_b` varchar(255) NOT NULL,
  `q4_opt_c` varchar(255) NOT NULL,
  `q4_opt_d` varchar(255) NOT NULL,
  `q4_answer` varchar(255) NOT NULL,
  `q5` varchar(255) NOT NULL,
  `q5_opt_a` varchar(255) NOT NULL,
  `q5_opt_b` varchar(255) NOT NULL,
  `q5_opt_c` varchar(255) NOT NULL,
  `q5_opt_d` varchar(255) NOT NULL,
  `q5_answer` varchar(255) NOT NULL,
  `q6` varchar(255) NOT NULL,
  `q6_opt_a` varchar(255) NOT NULL,
  `q6_opt_b` varchar(255) NOT NULL,
  `q6_opt_c` varchar(255) NOT NULL,
  `q6_opt_d` varchar(255) NOT NULL,
  `q6_answer` varchar(255) NOT NULL,
  `q7` varchar(255) NOT NULL,
  `q7_opt_a` varchar(255) NOT NULL,
  `q7_opt_b` varchar(255) NOT NULL,
  `q7_opt_c` varchar(255) NOT NULL,
  `q7_opt_d` varchar(255) NOT NULL,
  `q7_answer` varchar(255) NOT NULL,
  `q8` varchar(255) NOT NULL,
  `q8_opt_a` varchar(255) NOT NULL,
  `q8_opt_b` varchar(255) NOT NULL,
  `q8_opt_c` varchar(255) NOT NULL,
  `q8_opt_d` varchar(255) NOT NULL,
  `q8_answer` varchar(255) NOT NULL,
  `q9` varchar(255) NOT NULL,
  `q9_opt_a` varchar(255) NOT NULL,
  `q9_opt_b` varchar(255) NOT NULL,
  `q9_opt_c` varchar(255) NOT NULL,
  `q9_opt_d` varchar(255) NOT NULL,
  `q9_answer` varchar(255) NOT NULL,
  `q10` varchar(255) NOT NULL,
  `q10_opt_a` varchar(255) NOT NULL,
  `q10_opt_b` varchar(255) NOT NULL,
  `q10_opt_c` varchar(255) NOT NULL,
  `q10_opt_d` varchar(255) NOT NULL,
  `q10_answer` varchar(255) NOT NULL,
  `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`id`, `term`, `session`, `type`, `class`, `subject`, `instruction`, `q1`, `q1_opt_a`, `q1_opt_b`, `q1_opt_c`, `q1_opt_d`, `q1_answer`, `q2`, `q2_opt_a`, `q2_opt_b`, `q2_opt_c`, `q2_opt_d`, `q2_answer`, `q3`, `q3_opt_a`, `q3_opt_b`, `q3_opt_c`, `q3_opt_d`, `q3_answer`, `q4`, `q4_opt_a`, `q4_opt_b`, `q4_opt_c`, `q4_opt_d`, `q4_answer`, `q5`, `q5_opt_a`, `q5_opt_b`, `q5_opt_c`, `q5_opt_d`, `q5_answer`, `q6`, `q6_opt_a`, `q6_opt_b`, `q6_opt_c`, `q6_opt_d`, `q6_answer`, `q7`, `q7_opt_a`, `q7_opt_b`, `q7_opt_c`, `q7_opt_d`, `q7_answer`, `q8`, `q8_opt_a`, `q8_opt_b`, `q8_opt_c`, `q8_opt_d`, `q8_answer`, `q9`, `q9_opt_a`, `q9_opt_b`, `q9_opt_c`, `q9_opt_d`, `q9_answer`, `q10`, `q10_opt_a`, `q10_opt_b`, `q10_opt_c`, `q10_opt_d`, `q10_answer`, `date`) VALUES
(1, 'second_term', '', 'test', 'JSS1', 'English Language', 'Underline the adverbs in the following sentences', 'The choir sang beautifully in the church', 'sang', 'church', 'beautifully', 'choir', 'beautifully', 'The team played well', 'well', 'the', 'played', 'team', 'well', 'The woman quickly sent the boy away', 'boy', 'quickly', 'sent', 'the', 'quickly', 'The students answered the question correctly', 'correctly', 'question', 'answered', 'students', 'correctly', 'The king walked majestically', 'the', 'king', 'walked', 'majestically', 'majestically', 'The sound that glides from one sound to another is called __________________', 'vowel', 'pure vowel', 'consonant', 'diphthong', 'diphthong', 'A term used in grammar to indicate the time of the action or event is known as ________________', 'tense', 'verb', 'simple present', 'adjective', 'tense', 'She _______________ everyday.', 'eat', 'ate', 'eaten ', 'eats', 'eats', 'We ______________ every morning', 'ate', 'eats', 'eaten', 'eat', 'eat', 'He ________________ to church last sunday', 'goes', 'come', 'go', 'went', 'went', '2024-05-23 08:08:20'),
(2, 'second_term', '', 'test', 'JSS1', 'Civic Education', '', 'Which of the following is not an example of a self reliant business', 'Civil service', 'Candle making', 'Shoe making', 'Soap making', 'Civil service', 'Talent are rightly described as ______________', 'Magic', 'Physical challenge', 'Natural abilities', 'none of the above', 'Natural abilities', 'A person born in a country where his or her parents are citizens automatically becomes a _______________', 'citizen', 'foreigner', 'migrant', 'guest', 'citizen', 'Which of the following is not a type of citizenship', 'citizenship by birth', 'citizenship by force', 'citizenship by registration', 'citizenship by naturalisation', 'citizenship by force', 'In Nigeria, a citizen has _________________', 'limited right to vote', 'full right to vote', 'right to buy votes', 'right to engage in violence', 'full right to vote', 'A kind of value cherished by an individual is distinguished as ______________', 'moral values', 'society values', 'personal values', 'aesthesic values', 'personal values', 'Values in a society promotes the following except _________________', 'peace', 'hatred', 'cooperation', 'love', 'hatred', 'When we positively cooperate and live in peace with one another, we promote ______________', 'good values', 'fear', 'bad attitude', 'jealous', 'good values', 'Honesty means ________________', 'being honest', 'being dishonest', 'being educated', 'being married', 'being honest', 'Honesty often attract _____________', 'punishment', 'disrespect', 'respect', 'dishonesty', 'respect', '2024-05-23 08:08:20'),
(3, 'second_term', '', 'test', 'JSS1', 'Basic Technology', '', 'One of the following is a process of processing the material wood', 'peeling', 'timber growth', 'sew', 'forest', 'timber growth', 'Timbers are trees in the _________________', 'church', 'school', 'forest', 'market', 'forest', 'Wood suitable for engineering work is called ____________________', 'word', 'suitable', 'timber', 'work', 'timber', 'One of the instrument used for timber felling is _______________', 'chain', 'belt', 'chain saw', 'hoe', 'chain saw', 'The formula for calculating the percentage(%) of the water or moisture content in a wood or timber is given as _______________', '(wet - dry)/dry * 100/1', '(wet + dry)/dry * 100/1', '(wet / dry)/dry * 100/1', '(dry - wet)/dry * 100/1', '(wet - dry)/dry * 100/1', 'The feature that reduces the quantity or marketable value of a timber is known as _______________', 'growth', 'conversion', 'defect', 'preservation', 'defect', 'The process of applying chemical on wood or timber to prevent the attack of insect is known as ______________', 'preservation', 'seasoning', 'defect', 'attack', 'preservation', 'Determine the different between 6kg and 50kg ', '1kg', '2g', '3kg', '10kg', '10kg', 'Natural seasoning is also known as ______________', 'nature', 'air seasoning', 'kiln seasoning', 'natural seasoning', 'air seasoning', 'One of these is a method applying timber preservative', 'spraying', 'cutting', 'washing', 'watering', 'spraying', '2024-05-23 08:08:20'),
(4, 'second_term', '', 'test', 'JSS1', 'CCA', '', 'Mat and raffia works are referred to as _____________', 'crafts', 'painting', 'ceramics', 'pencil', 'crafts', 'Raffia and cotton are fibres most widely used for _______________ in Nigeria', 'dyeing', 'weaving', 'painting', 'jumping', 'weaving', 'The following are needed for cane weaving EXCEPT __________________', 'cane stick', 'paper', 'cutting knife', 'nail', 'paper', 'The mixing of dye chemical in tie &amp; dye process is referred to as ___________________', 'mixing', 'vatting', 'dye stuff', 'salt', 'vatting', 'An instrument/tool used in spreading ink on a silk screen mesh is __________', 'squeege', 'lino', 'mesh', 'maquette', 'squeege', 'In batik design, the materials used as a resist is ________________', 'dye', 'wax', 'paint', 'rope', 'wax', 'A pounded wet paper mixed with starch is _________________', 'round', 'objects', 'paper mache', 'starch', 'paper mache', 'Two main materials for paper mache are _________________', 'starch and paper', 'starch and crum', 'starch and leave', 'starch and plate', 'starch and paper', 'Dyed cloth can be used in making ___________________', 'paint', 'chain', 'dress', 'teaching', 'dress', 'paper mache is done by mixing pounded paper with ____________', 'starch', 'evostic', 'clay', 'paint', 'starch', '2024-05-23 08:08:20'),
(5, 'second_term', '', 'test', 'JSS2', 'Basic Science', '', 'Anything released on air that makes breathing difficult is known as ________________', 'Iodine', 'carbon (iv) oxide', 'oxygen', 'air pollutant', 'air pollutant', 'Which of these substances is a solid air pollutant _________________', 'rock', 'faeces', 'wood', 'cement particles', 'cement particles', 'Bush burning is a way of practicing ______________', 'afforestation', 'irrigation', 'social amenities', 'air pollution', 'air pollution', '_______________ is one of the useful soil living organisms in the soil', 'ant', 'earthworm', 'scorpion', 'snake', 'earthworm', 'These are examples of soil pollutant except _______________', 'oil spillage', 'nylon', 'scraps', 'seed planting', 'seed planting', '_____________ is one of the control measures against soil pollution', 'good sanitation practice', 'bush burning', 'deforestation', 'practicing oil spillage', 'good sanitation practice', 'The short form of Information and Communication Technology is', 'ITC', 'CIT', 'ICT', 'TCI', 'ICT', 'The name of the enzyme which act in the mouth is _____________', 'ptyalin', 'pepsin', 'rennin', 'lipase', 'ptyalin', 'Digestion of food ends where', 'mouth', 'small intestine', 'large intestine', 'gall bladder', 'small intestine', 'Bile salt helps to break down _______________', 'starch', 'protein', 'fats and oil', 'peptone', 'fats and oil', '2024-05-23 08:08:20'),
(6, 'second_term', '', 'test', 'JSS2', 'Business Studies', '', 'An insurance policy that deals with breaking stealing from a house or shop is known as _________________', 'marine', 'burglary', 'fire insurance', 'vehicle insurance', 'burglary', 'The insurance policy which covers goods by sea is known as ____________ insurance', 'marine', 'vehicle', 'burglary', 'fire', 'marine', 'The seller records his daily cash sales in a book called ____________', 'price list', 'delivery note', 'cash account', 'cash register', 'cash register', 'One of the following is an example of large retailer _______________', 'stall holder', 'kiosk owner', 'supermarket', 'hawker', 'supermarket', 'A trader who buy goods in small quantities from wholesaler is called _____________', 'producer', 'retailer', 'wholesaler', 'consumer', 'retailer', 'One of the following is not a type of bank ___________________', 'commercial', 'Union bank', 'mortgage bank', 'agricultural bank', 'Union bank', 'The creation of goods and services for the satisfaction of human wants is known as ______________', 'produce', 'market', 'production', 'trade', 'production', 'The two types of cheque are _________________', 'open cheque and cover cheque', 'cross cheque and close cheque', 'bank cheque and open cheque', 'cross cheque and open cheque', 'cross cheque and open cheque', 'Which of the following is not among the departments in an organisation?', 'trading department', 'sales department', 'account department', 'personnel department', 'trading department', 'Farming is an example of ________________ production', 'extractive', 'constructive', 'service', 'commercial', 'extractive', '2024-05-23 08:08:20'),
(7, 'second_term', '', 'test', 'JSS2', 'Computer Studies', '', 'The numeral system of representing numbers of a given set using digits in a consistent manner is known as ________________', 'numeral system', 'basic numbering', 'number values', 'number cases', 'numeral system', 'The hexadecimal system represents numbers using ________________ digits', '10', '2', '8', '16', '16', 'Base 2 is also referred to as _____________________', 'binary', 'decimal', 'octal', 'denary', 'binary', 'Convert 42 to base 2', '10001', '111012', '101010', '100100', '101010', 'The smallest unit of storage in computer is called __________________', 'byte', 'character', 'bits', 'word', 'bits', '1 kilobyte is equivalent to _______________________ bytes', '1000', '1020', '1340', '1024', '1024', 'Programs written in _______________ language are executed without interpretation', 'Machine', 'Assembly', 'C++', 'Java', 'Machine', 'The representation of solutions to a problem or job steps is _____________', 'steps', 'procedures', 'algorithm', 'program', 'algorithm', 'Which of these is not a high level language', 'C++', 'Java', 'Igbo', 'Python', 'Igbo', 'One nibble is equivalent to _______________ byte', '1024', '1/2', '1/3', '8', '1/2', '2024-05-23 08:08:20'),
(8, 'second_term', '', 'test', 'JSS1', 'French Language', '', 'Le frere de mon pere est mon __________', 'oncle', 'grand-pere', 'consin', 'neven', 'oncle', 'Les animant sanvages se tronvent dans la ________________', 'piscine', 'foret', 'maison', 'a l ecole', 'foret', 'The weather is very cold. We say _________________________', 'il fait tres chand', 'il plent', 'il fait tres froid', 'il neige', 'il fait tres froid', '15 + 30 = _________________', 'quarante', 'quarante-cinq', 'cin quante-cinq', 'quatorze-cinq', 'quarante-cinq', 'La soeur de ma mere est ma _______________', 'tante', 'niece', 'cousine', 'amie', 'tante', 'Le huitieme mois de l&#039; annee c&#039;est _______________', 'janvier', 'avril', 'aout', 'mars', 'aout', 'Le mois de Novembre a ________________ jours', 'trente', 'vingt', 'vingt-huit', 'trente et un', 'trente', 'Un chat habite dans la ______________', 'a l&#039;ecole', 'foret', 'maison', 'a l&#039;eglise', 'maison', 'Les pays ___________ parlent le Francais', 'francophones', 'megaphones', 'anglophones', 'francaisphones', 'francophones', 'Un tableam c&#039;est ___________ en anglais', 'table', 'board', 'textbook', 'pencil', 'board', '2024-05-23 08:08:20'),
(9, 'second_term', '', 'test', 'JSS1', 'Social Studies', '', 'The process of socialization starts from ____________', 'life to death', 'birth to death', 'primary to secondary', 'home to church', 'birth to death', 'Government helps in socialization by making __________', 'transactions', 'correction', 'punishment', 'laws', 'laws', 'Road safety club helps to control _________ on the road', 'accident', 'traffic', 'officials', 'students', 'traffic', 'Pedestrains, cyclists, motorists are also known as road ____________', 'labourers', 'workers', 'users', 'police', 'users', 'The first cult group to be introduced in Nigeria schools was', 'Buccanears', 'Pyrates', 'dragons', 'black bra', 'Pyrates', 'HIV/AIDS, Syphilis, Gonorrhea are examples of ____________ diseases', 'respiratory', 'circulatory', 'digestive', 'venereal', 'venereal', 'HIV affects the _______________ system of the body', 'viral', 'immune', 'sexuality', 'reproductive', 'immune', 'These are forms of corruption except', 'bribery', 'embezzlement of public fund', 'extortion', 'rigging', 'rigging', 'Contemporary social problems can lead to these except', 'destruction of lives and property', 'increase in crime', 'insecurity and fear', 'economic growth', 'economic growth', 'National unity and integration helps to sustain', 'terrorism', 'democracy', 'corruption', 'poverty', 'democracy', '2024-05-23 08:08:20'),
(10, 'second_term', '', 'test', 'JSS1', 'Igbo', 'Zaa ajụjụ niile site n&#039;ihọrọ nke bụ aziza', 'Agwa ọma pụtara akpara maagwa ___________ nke mmadụ na akpa', 'dimma', 'adighi mma', 'jọrọ njọ', 'zoro ezo', 'dimma', 'Ezigbo umụaka na-akpa agwa _________', 'ọjọọ', 'ọma', 'udo', 'ogba aghara', 'ọma', 'Agwa ọma gunyere _______', 'izu ohi', 'ikwa iko', 'ikwu eziokwu', 'ịlụ ọgụ', 'ikwu eziokwu', 'Ọghọ dị na nwata ikpa ajọ agwa gunyere __________ ', 'onyinye ', 'oriri ', 'ntaramahụhụ ụtari', 'mbulizelu', 'ntaramahụhụ ụtari', 'E nwere ụdi agumagu __________ n&#039;asụsụ igbo', 'anọ', 'atọ', 'abụọ', 'ise', 'abụọ', 'Aha ọzọ e nwere ike ịkpọ agụmagụ ugbua bu _________  ', 'agụmagụ ederede', 'agụmagụ', 'ebiri ebi', 'ahụrụ anya', 'agụmagụ ederede', 'Ekere agụmagụ ọdinala ụzọ _______', 'atọ', 'abụọ', 'ise', 'anọ', 'atọ', 'Nkenudi agụmagụ odinaala bụ ________ ', 'ekwe', 'ejije', 'umuaka', 'noovl', 'ejije', 'A na-ede agụmagụ ___________ n&#039;akwụkwọ  ', 'odinaala', 'ugbua', 'odide', 'agụmagụ', 'ugbua', 'Tinye akara udaolu na okwu a (akwa - (cry))   ', '&frasl;  &setminus;', '&frasl; &frasl;', '&frasl; &mdash;', '&setminus; &setminus;', '&frasl; &frasl;', '2024-05-23 08:08:20'),
(11, 'second_term', '', 'test', 'JSS2', 'CRS', '', 'The word &quot;Beatitude&quot; means __________________', 'special reward', 'blessedness or blessings', 'righteous', 'joy', 'blessedness or blessings', 'The enemy who sowed the tares is the ________________', 'angels', 'devil', 'unfaithful servants', 'envious neighbours', 'devil', 'In the parable of the sower, the seed represents ___________', 'word of God', 'the field', 'grains like rice, beans', 'seedtrees', 'word of God', 'Identify the parable of the kingdom from these', 'the rich fool', 'prodigal son', 'the wheat and tares', 'Richman and Lazarus', 'the wheat and tares', 'The seeds fell on these places EXCEPT', 'pathway', 'rocky ground', 'bank of the river', 'thorns', 'bank of the river', 'After he had finished all that he had, one of these natural problems started in the country', 'famine', 'global economic melt down', 'epidemic disease', 'civil war', 'famine', 'When life becomes very difficult and unbearable, the prodigal son &quot;came to himself&quot; this means ', 'He became mad', 'He regretted', 'He repented', 'He sleeped up', 'He repented', 'In the parable of the unforgiving steward Jesus told peter that he should forgive his brother ___________________ a day', 'seven times seven times', 'seventeen times seven', 'seventy times seventy times', 'seventy times seven times', 'seventy times seven times', 'The first thing the richman requested from Abraham was ___________________', 'to preach to his brothers', 'a drop of water', 'to set him free', 'to give him food', 'a drop of water', 'Identify one of these parables as parable of the kingdom taught by Christ', 'the parable of the lost sheep', 'the parable of the lost coin', 'the parable of the sower', 'the parable of the rich fool', 'the parable of the sower', '2024-05-23 08:08:20'),
(12, 'second_term', '', 'test', 'JSS2', 'English Language', '', 'A narrative essay is a story that is narrated verbally or __________________', 'quantitative', 'written', 'orally', 'eassy', 'written', 'An example of adjective is ____________________', 'poor', 'quickly', 'sentence', 'adjective', 'poor', 'A type of adjective is _____________', 'mini adjective', 'subject adjective', 'adjective of numbers', 'adjective of adverb', 'adjective of numbers', 'An example of &frasl; iə &frasl; sound is ______________', 'words', 'shoe', 'pencil', 'India', 'India', 'A _____________ is a form of the verb that allows you to express time', 'narrative ', 'event', 'tense', 'past tense', 'tense', 'The _______________ is used when you want to say that something has already happened and was completed in the past', 'simple past tense', 'present tense', 'future tense', 'none of the above', 'simple past tense', 'He _____________ from London sometime ago', 'comes', 'come', 'came', 'go ', 'came', 'The Super Eagles ________________ the match', 'win', 'has win', 'watch', 'won', 'won', 'I _________________ my teeth everyday', 'brushes', 'brushed', 'brush', 'brash', 'brush', 'Who is the author of &quot;Strong Decision&quot;', 'Adamu C U', 'Udoye Uche B', 'Amadi Y C', 'NNamani Eunice', 'Udoye Uche B', '2024-05-23 08:08:20'),
(13, 'second_term', '', 'test', 'JSS2', 'HPE', '', 'The first world table tennis championship took place in ___________ year', '1970', '1926', '1927', '1928', '1927', 'The planned programme which provides knowledge, skills and attitude that enables an individual to avoid accident is called _______________', 'safety', 'safety education', 'accident', 'school accident', 'safety education', 'Home accident is called ____________________', 'domestic accident', 'school accident', 'occupational accident', 'market', 'domestic accident', 'A break in a bone is called ______________', 'dislocation', 'fracture', 'sprain', 'strain', 'fracture', 'The stroke that involves an immediate return of the ball as it lands on the table is __________________', 'chop', 'service', 'drop shot', 'half volley', 'half volley', 'The process of receiving the ball in the game as it is in play is ________________________', 'service', 'let', 'lob', 'rally', 'rally', 'In table tennis holding of the bat is known as ______________', 'holder', 'grip', 'service', 'skill', 'grip', 'Taking ball at random is one of the function of _____________', 'referee', 'umpire', 'stroke counter', 'assistant umpire', 'umpire', 'The damage of any part of the body during sports is called _________________', 'accident', 'wound', 'cut', 'sports injury', 'sports injury', 'Road accident is also known as ___________________ accident', 'occupational', 'traffic', 'domestic', 'school', 'traffic', '2024-05-23 08:08:20'),
(14, 'second_term', '', 'test', 'JSS2', 'History', '', 'Ghana means ______________________', 'powerful', 'industry', 'the king', 'war chief', 'war chief', 'One of the following band of invaders attacked the empire of Ghana', 'the Fulani', 'the Hausa', 'the Almoravids', 'the berbers', 'the Almoravids', 'The language of Soninke people was __________________', 'Tunka manin', 'Mande', 'Susu', 'Bozo', 'Mande', 'The ________________ comprises council of ministers who assisted the kings', 'the farmers', 'the kings', 'the nobles', 'craftsmen', 'the nobles', 'The capital of ancient Ghana was __________________', 'Mande', 'Soninke', 'Kumbi-Saleh', 'Wangara', 'Kumbi-Saleh', 'Mali empire was believed to have developed from the state of _______________', 'Soninke', 'Mande', 'Madin Kara', 'Malinke', 'Malinke', 'Sundiata Keita died in the year ______________', '1235AD', '1245AD', '1255AD', '1265AD', '1255AD', 'Mali empire was founded by _____________________', 'Sundiata Keita', 'Mansa Musa', 'Samariguru', 'Mansa Uli', 'Sundiata Keita', 'At what age did Sundiata Keita became the emperor of Mali', '16', '17', '18', '19', '18', 'Jihad means _____________________', 'war', 'holy war', 'journey', 'warrior', 'holy war', '2024-05-23 08:08:20'),
(15, 'second_term', '', 'test', 'JSS2', 'Social Studies', '', 'E-mail stands for ', 'Electrical mail', 'Engineering mail', 'Electronic mail', 'Education mail', 'Electronic mail', 'The world wide international network of computer is ', 'GSM', 'E-mail', 'phone', 'Internet', 'Internet', 'ICT has made the world a', 'Continent', 'global village', 'network city', 'rural city', 'global village', 'Rainfall, Ocean, Lake, river, sea are ______________________ sources of water', 'clean', 'artificial', 'natural', 'best', 'natural', 'Fishermen should avoid using chemicals in', 'market', 'water', 'fishing', 'poultry', 'fishing', 'The visible mass of water droplets suspended in the air is called ', 'rainfall', 'fog', 'haze', 'cloud', 'cloud', 'Humidity is measured with a', 'hydrometer', 'barometer', 'sundial', 'hygrometer', 'hygrometer', 'The degree of hotness or coldness of a place is known as', 'thermometer', 'temperature', 'pressure', 'humidity', 'temperature', 'Weather is a casual remark about the', 'Sun', 'atmosphere', 'earth', 'water', 'atmosphere', 'Itshe Kiri people call God ', 'Chukwu', 'Olorun', 'Abasi', 'Oritshe', 'Oritshe', '2024-05-23 08:08:20'),
(16, 'second_term', '', 'test', 'JSS2', 'Mathematics', '', 'Simplify (-5) x (3f)', '-15f', '15f', '-8f', '8f', '-15f', 'Remove bracket from 3(m - 2)', '3m + 5', '3m - 5', '3m + 6', '3m - 6', '3m - 6', 'if n = 4, m = 3 and x = 10. Find the value of mx + n', '30', '14', '17', '34', '34', 'A certain number is added to 7 and then divided by 12. The result is 4. Find the number', '12', '41', '48', '24', '41', 'Solve this equation 1/y + 1/4  =  1/3', '3', '4', '12', '15', '12', 'Simplify 1/p + 1/p', '2p/p', 'p/2', '1/p', '2/p', '2/p', 'Which of the following is not an algebraic term', '3x + 2', '6y', '9ts', '3rv', '3x + 2', 'Simplify 4a/3x - 2a/3y =', '2a/3xy', '6a/3x', '(4ay-2ax)/3xy', '2xy/3xy', '(4ay-2ax)/3xy', 'Factorise vw - uw', 'v(w - u)', 'u(w + v)', 'w(v + u)', 'w(v - u)', 'w(v - u)', 'Expand (5d - 4)(5d - 6)', '25d^2 - 50d + 24', '10d^2 - 10d + 24', '10d^2 + 10d + 24', '25d^2 + 50d + 24', '25d^2 - 50d + 24', '2024-05-23 08:08:20'),
(17, 'second_term', '', 'test', 'JSS1', 'Computer Studies', '', 'Coeries are examples of __________________ counting devices', 'early', 'late', 'mechanical', 'electronic', 'early', 'First generation computers used ____________ technology', 'transistor', 'vacuum tube', 'AI', 'IC', 'vacuum tube', 'Napier&#039;s bone was invented by __________________', 'John Thomas', 'Ken Napier', 'John Napier', 'Napier James', 'John Napier', 'Pascaline was invented in the year ______________________', '1642', '1942', '1960', '1891', '1642', 'Leibniz Wilhelm invented a machine called ________________', 'step reckoner', 'pascaline', 'punched card', 'jaquard loom', 'step reckoner', 'The father of computer is known as ______________', 'John Mauculy', 'Blaise Pascal', 'Grace Johns', 'Charles Babbage', 'Charles Babbage', 'AI is the short for _________________', 'Automatic Inspection', 'Artificial Instruction', 'Artificial Intelligence', 'Art Intelligence', 'Artificial Intelligence', 'Second generation computers existed between _________________ and _______________', '1954 and 1906', '1956 and 1963', '1960 and 1963', '1963 and 2023', '1956 and 1963', 'Describing computer as IPO system, P means ____________________', 'program', 'printer', 'process', 'plotter', 'process', 'Input and Output devices are collectively referred to as _____________________', 'Computer system', 'System unit', 'Devices', 'Peripherals', 'Peripherals', '2024-05-23 08:08:20'),
(18, 'second_term', '', 'test', 'JSS1', 'Business Studies', '', 'All EXCEPT one are qualities of a clerical staff _______________', 'punctuality', 'obedient', 'honest', 'disobedient', 'disobedient', 'The following are forms of business organisation EXCEPT one ___________', 'sole proprietorship', 'trade', 'partnership', 'co-operative society', 'trade', 'Which of the following is not an advantage of a sole proprietorship ? _________________', 'easy to establish', 'easy decision making', 'small capital to establish', 'none of the above', 'none of the above', 'One of the following is NOT a division of occupation __________________', 'extractive', 'commercial', 'entrepremier', 'fishing', 'entrepremier', 'The following are factors that cause people to tell lies EXCEPT one ________________', 'being reliable', 'gossiping', 'honesty', 'good behaviour', 'gossiping', 'All EXCEPT one are the consequences of not being truthful ___________________', 'you are well respected', 'you are not trusted', 'you are considered unreliable', 'people will look down on you', 'you are well respected', 'A business established, owned and financed by one person is known as ___________________', 'cooperative society', 'partnership', 'sole proprietorship', 'public enterprises', 'sole proprietorship', 'The buying and selling of goods between two or more countries is known as _________________ trade', 'export', 'foreign', 'import', 'home', 'foreign', 'The formation of a partnership is always supported by a legal document called ____________', 'sleep partner', 'limited partner', 'partnership deed', 'ordinary partnership', 'partnership deed', 'One of the following is NOT factors of production __________________', 'land ', 'labour', 'capital', 'partnership', 'partnership', '2024-05-23 08:08:20'),
(19, 'second_term', '', 'test', 'JSS1', 'Mathematics', '', 'Simplify 4.565 + 0.05', '91.31', '4.615', '191.6', '81.321', '4.615', 'Express  342 base six to base 10', '44', '57', '134', '342', '134', 'Convert 19 base ten to base 2', '10001', '10111', '10011', '10110', '10011', 'Write in figure: Three hundred and thirty-two thousand and five', '33205', '332005', '30032005', '3320005', '332005', 'What is the place value of 9 in 2984?', 'nine hundred', 'nine thousand', 'nine tens', 'nine units', 'nine hundred', 'Add 10111 base two and 11101 base two', '10110', '110100', '101110', '1110010', '110100', 'Convert 25% to fraction in it&#039;s lowest term', '3/5', '1/4', '3/4', '1/2', '1/4', 'Convert 1/2 to decimal', '0.5', '0.25', '0.75', '2.5', '0.5', 'Subtract 11011 base two from 11110 base two', '11', '99', '101', '110', '11', 'Binary numbers are base ___________ numbers', '4', '8', '2', '3', '2', '2024-05-23 08:08:20'),
(20, 'second_term', '', 'test', 'JSS1', 'Agric Science', '', 'A ruminant animal has _________________ stomach chambers', '4', '3', '2', '1', '4', 'Crops which mature  within two years are called ____________ crops', 'annual', 'byiennial', 'biennial', 'dicot', 'biennial', 'Another name for ruminant animal is called _________________', 'mongastric', 'polygastric', 'monocropping', 'gonorrhea', 'polygastric', 'Non-ruminant digestive system is so similar to that of _________________', 'goat', 'cow', 'man', 'sheep', 'man', 'The cost of feeding is high in ________________ animal', 'ruminant', 'polygastric', 'cattle', 'non-ruminant', 'non-ruminant', 'Animal that live both on the land and the water is called ____________', 'amphibians', 'terrestrial', 'aquatic', 'guard', 'amphibians', 'Farm animals that are very big in size are called ____________ animals', 'small sized', 'little sized', 'large sized', 'monogastric', 'large sized', 'The fruit that is known as &quot;carica papaya&quot; is _______________ ', 'orange', 'mango', 'apple', 'paw-paw', 'paw-paw', 'Animals that are kept mainly for milk production are called ______________', 'dairy', 'work', 'pet', 'aquatic', 'dairy', 'When the undigested grass in the rumen enters reticulum and back to the mouth and the animal begins to chew the grass again is called _____________', 'chewing gum', 'chewing cud', 'chewing mouth', 'chewing stick', 'chewing cud', '2024-05-23 08:08:20'),
(21, 'second_term', '', 'test', 'JSS1', 'History', '', 'The NOK culture was discovered in the year ___________', '1958', '1928', '1947', '1938', '1928', 'The following are centres of ancient civilization EXCEPT', 'NOK', 'Kaduna', 'Igbo-ukwu', 'ILe-ife', 'Kaduna', 'The political head of Ife is _______________ ', 'Alaafin', 'Ooni', 'Ets', 'Oba', 'Ooni', 'The cradle of yoruba civilization was at __________', 'Oshogbo', 'Ibadan', 'ILe-Ife', 'Egba', 'ILe-Ife', 'The first Ife works to be discovered were ___________', 'Human heads', 'Glass beads', 'Goat head', 'Animal heads', 'Glass beads', 'The brass and terra-cotta heads of Ife had tribal marks called ____________', 'start', 'trate', 'striations', 'traits', 'striations', 'The Yoruba nation originated from Ife through the legendary figure of _______________', 'Amina', 'Zaria', 'Chineke', 'Oduduwa', 'Oduduwa', 'The Benin had a ruling line or dynasty made up of kings called _____________', 'ogisa', 'ogis', 'ogiso', 'osha', 'ogiso', 'NOK culture is also found in these locations EXCEPT', 'Taruga', 'Kagara', 'Yelwa', 'Aba', 'Aba', 'The NOK culture was discovered by a group of _____________', 'Farmers', 'Traders', 'Tin miners', 'historians', 'Tin miners', '2024-05-23 08:08:20'),
(22, 'second_term', '', 'test', 'JSS1', 'Basic Science', '', 'The practice of restraining one from all aspect of sexual intercourse is called _________________', 'social', 'abstinence', 'sexual intercourse', 'STIs', 'abstinence', 'A person that has self confidence is under ______________ esteem', 'low self', 'middle self', 'high self', 'none of them', 'high self', 'Factors that affects self esteem are the following EXCEPT ________________', 'Gender', 'environment', 'media', 'sport', 'sport', 'Another name for menstruation is ________________', 'monopause', 'menses', 'wet dream', 'festis', 'menses', 'One of the factor __________________ is a similarity between boys and girls during puberty', 'body odor', 'growth of beard', 'ejaculation', 'enlargement of scrotum', 'body odor', 'The statement that says &quot;it is not good for boys to have wet dreams &quot; is referred to as ____________', 'culture', 'myth', 'fact', 'truth', 'myth', '________________ is one of the classification of matter', 'living things', 'solid', 'gas', 'stone', 'living things', 'A substance that can change from solid to gas without changing first to liquid state is called _____________', 'solid', 'liquid', 'gas', 'sublimation', 'sublimation', 'One of these substances sublime __________', 'camphor', 'water', 'soap', 'gas', 'camphor', '______________ is an example of non-living things', 'soil', 'tree', 'cow', 'ant', 'soil', '2024-05-23 08:08:20'),
(23, 'second_term', '', 'test', 'JSS1', 'HPE', '', 'Football association became a legalized profession in ______________ year', '1904', '1963', '1885', '1996', '1885', 'Examples of non locomotive movement are these except _______________', 'bending', 'twisting', 'stretching', 'running', 'running', 'The type of fundamental movement that involve moving from one place to another is known as ________________ movement', 'locomotor', 'gymnastics', 'water sport', 'non-locomotor', 'locomotor', 'The act of putting the ball into play is ____________ ', 'volleying', 'digging', 'retrieving', 'service', 'service', 'Football is also known as _________________', 'Tsechu', 'Soccer', 'Ekpeskyros', 'Gymnastics', 'Soccer', 'To co-ordinate the substitution of a player is one of the function of __________________', 'coach', 'referee', 'umpire', 'assistant referees', 'umpire', 'These are types of service in volley ball except _________________', 'Tennis service', 'Side arm service', 'Under arm service', 'Volleying', 'Volleying', 'Another name for pre-colonial sports is _____________________', 'Traditional sports', 'football', 'Tsechu', 'Abula', 'Traditional sports', 'The man that invented Abula in Nigeria was _________________', 'Dr. J.C Omoruan', 'A.Oduyale', 'Mt Elias Yusuf', 'A. Ajiduah', 'Mt Elias Yusuf', 'The official that uses yellow card to book a player in football is ________________', 'Umpire', 'Referee', 'Linesmen', 'Coach', 'Referee', '2024-05-23 08:08:20'),
(24, 'second_term', '', 'test', 'JSS1', 'CRS', '', 'The willingness or readiness to accept and carry out a given instruction, rules, commands or order is called ___________________', 'Displine', 'Agreement', 'Obedience', 'Understanding', 'Obedience', 'When Abraham answered God&#039;s call and received hos promises he was __________ years old', 'Hundred', 'Ninety-nine', 'Seventy-five', 'Seventeen', 'Seventy-five', 'How old was Abraham when Isaac was born ______________', '85 years', '50 years', '75 years', '100 years', '100 years', 'Sarah had a son at ___________ years', 'Ninety years', 'Eighty years', 'Sixty years', 'Hundred years', 'Ninety years', 'The descendant of Abraham through whom the nation of Israel was born is ________________', 'Isaac', 'Esau', 'David', 'Jacob', 'Isaac', 'Joseph was sold to the Ishmaelite for ________________ shekels of silver', 'Thirty', 'Twenty', 'Forty', 'Twenty-five', 'Twenty', '________________ decided to go back to Moab when she discovered that her future is not promising', 'Ruth', 'Naomi', 'Orpah', 'Rahah', 'Orpah', 'One of the sad experience Joseph had during his service at portiphar&#039;s house was ___________________', 'Hunger and starvation', 'Imprisonment', 'Humiliation and nakedness', 'Hard labour as a slave', 'Imprisonment', 'Ruth the Moabites eventually because the ___________ of Jesus Christ', 'Step -Mother', 'Ancestress', 'Mother-in-Law', 'Ancestor', 'Imprisonment', 'The father of Abraham was called _____________', 'Terah', 'Haran', 'Nahor', 'Lemech', 'Terah', '2024-05-23 08:08:20'),
(25, 'second_term', '', 'test', 'JSS1', 'Security Education', '', 'Individuals expressing their dissatisfactions due to unfair judicial rulings from the law court and unjust imprisonment is as a result of _____________', 'politics', 'unemployment', 'poor judgement', 'corrupt judiciary and prison system', 'corrupt judiciary and prison system', '_____________ is a state of being jobless which often leads people to commiting crimes', 'politics', 'poor judgement', 'unemployment', 'corrupt judiciary and prison system', 'unemployment', 'Historically __________________ brought about the advancement in production process', 'labour', 'movement', 'technology', 'industrialization', 'industrialization', 'General causes of common crimes includes all except _________________', 'poverty and stealing', 'poverty and unemployment', 'human weakness and poverty', 'peer pressure and politics', 'poverty and stealing', 'A state of unhappiness and low morale is known as _________________', 'depression', 'peer infulence', 'psychosis', 'depression', 'depression', 'An emotional wound is known as ________________', 'traumatic stress', 'depression', 'psychological factor', 'psychosis', 'traumatic stress', '________________, ____________________ and __________________ are the specific causes of common crimes.', 'psychological, psychosis and political', 'peer pressure, politics and poverty', 'psychological, human weakness and socio-economic', 'social and economic, biological and psychological', 'social and economic, biological and psychological', '____________ and ____________ are examples of social reactions to crime.', 'feeling of insecurity and fear of being alone', 'love of family members and acceptance by the community', 'social upliftment and integration', 'financial stability and educational qualification', 'feeling of insecurity and fear of being alone', '______________ and _________ are effects of common crimes in the community', 'lack of local involvement and poor academic performance', 'feeling of insecurity and dissatisfaction', 'economic losses and untimely death', 'it can lead one into prison and disruption of unity', 'feeling of insecurity and dissatisfaction', 'physical reactions to crimes includes all EXCEPT ____________', 'fear and anxiety', 'muscle pain', 'difficulty in eating', 'headaches', 'fear and anxiety', '2024-05-23 08:08:20'),
(26, '3rd Term', '2023/2024', 'test', 'JSS1', 'English Language', '', 'A word used instead of a noun in a sentence is called a', 'noun', 'verb', 'pronoun', 'adjective', 'pronoun', 'Underline the following pronouns in the following sentences from no 2- 6. Uche did the drawings himself', 'did', 'drawing', 'the', 'himself', 'himself', 'This is the student who won the prizehis', 'This', 'who', 'won', 'student', 'who', 'Those are the buildings', 'buildings', 'those', 'are', 'they', 'those', 'Whose are those shirts', 'whose', 'shirts', 'are', 'those', 'whose', 'This is the bag which a bought for you', 'This', 'bag', 'bought', 'which', 'which', 'The essay that tells a story is called `', 'descriptive essay', 'narrative essay', 'narrative essay', 'argumentative', 'narrative error', 'You can go on, I _______ what you are saying ', 'can hear', 'would hear', 'heard', 'I&#039;m hearing', 'can heaf', 'A verb can be regular _______', 'tense', 'irregular', 'base form', 'past', 'irregular', 'Regular verbs form their part participle byadding___________', '-e', '-th', '-y', '-ed', '-ed', '2024-05-23 08:08:20'),
(27, '3rd Term', '2023/2024', 'test', 'JSS1', 'CRS', 'ANSWER ALL', 'On the Seventh day of creation, God ____________________________', 'created sea animals', 'created human beings', 'created vegetation', 'rested from his work', 'rested from his work', 'The legitimate and voluntary union between a matured man and woman is called_________________________', 'Husband', 'Institution', 'Marriage', 'Home', 'Marriage', 'Every male child born to Abraham must be circumcised on the __________ day', '10th', '7th', '8th', '3rd month', '8th', 'Qualities of good and faithful service are these EXCEPT ONE', 'Selflessness', 'Honesty', 'Stealing', 'God fearing', 'Stealing', 'In the school, the child learns ______________ education ', 'Informal', 'Formal', 'Relationship', 'Citizen', 'Formal', 'The School is the next important agent of _______________ of the child after the ________________', 'Morals/family', 'Community/student', 'Socialization/family', 'Principal/vice-principal', 'Socialization/family', 'The consequences of choosing bad friends are these EXCEPT', 'lead to cultism', 'patient spirit', 'lead to prostitution', 'laziness', 'patient spirit', 'The friendship between David and Jonathan had a lasting experience and it extended to their children called', 'Joseph', 'Mephibosheth', 'Amalekite', 'Amalekite', 'Mephibosheth', '_______________ is a group of people who live in a known defined territory', 'Israel', 'family', 'community', 'customs', 'community', 'The community leader in charge of your house is called', 'father', 'Igwe', 'Ward leader', 'Elders', 'father', '2024-05-23 08:08:20'),
(28, '3rd Term', '2023/2024', 'test', 'JSS1', 'CCA', '', 'the combination of two 2 or more sounds heard at the same time in proper order is called', 'harmony', 'melody', 'clef', 'major', 'harmony', 'the music used for healing is known as _______________ music', 'popular', 'folk', 'social', 'palliative', 'palliative', 'music is a universal language of the  ______________________', 'point', 'soul', 'sacred', 'Bimp', 'soul', 'what is the name of the first line in the treble stave?', 'C', 'D', 'E', 'G', 'E', 'Difference of pitch is made clear in music by the use of ___________________________', 'stave', 'clef', 'key', 'natural', 'stave', 'A piece of music can be transcribed from staff notation to ______________________________', 'pietc notation', 'Solfa notation', 'G notation', 'folk notation', 'Solfa notation', 'the rest sign above is _______________________ rest', 'minim', 'semi breve', 'quaver', 'breve', 'minim', 'chromatiei scale has _______________________________ notes', '10', '12', '13', '16', '13', 'A scale is a series of ________________________________________ arranged in  alphabetical order', 'notes', 'dots', 'sharp', 'flat', 'notes', 'the symbol for double sharp is ________________________________                                                                                                                  ', '#', 'h', 'X', 'bb', 'X', '2024-05-23 08:08:20'),
(29, '3rd Term', '2023/2024', 'test', 'JSS1', 'Home Economics', '', 'carbohydrates are described as __________________________________________', 'body building food', 'protective food', 'energy', 'giving food', 'Energy', 'keeping the natural balance of the body aligned is called ____________________________________', 'posture', 'position', 'positive post', '______', 'posture', 'the organ for hearing is known as _______________________________________________', 'eye', 'ear', 'nose', '___________', 'ear', '__________________________________________ is a regular pattern of eating the same food always to maintain good health', 'food', 'diet', 'feeding and eating habit', '_________', 'feeding and eating habit', 'any substances added to food at the time of processing or preparation to become part of food is __________________________________', 'food addictive', 'drug abuse', 'healthy eating', '__________', 'food addictive', 'the intentional improper use of a drugs is called ______________________________________', 'self medication', 'drug abuse', 'scarification', '_________', 'drug abuse', 'the act of relaxing without sleeping is __________________________________________', 'fatigue ', 'health', 'rest', '___________', 'rest', 'the result from choosing nutritious food in conscious way is known as ___________________________________________', 'eating habit ', 'healthy feeding habits', 'unhealthy feeding habits', '____________', 'healthy feeding habits', 'one of the factors that affect healthy feeding practices can be say to ______________________________________', 'eating adequate diet', 'kwashiorkor', 'marasmius', '__________', 'eating adequate diet', 'one of this is correct in practicing healthy eating habits ______________________________________', 'do not talk with food in your mouth', 'do not wash your food before and after meals', 'do not chew your food properly', '____________', 'do not talk with food in your mouth', '2024-05-23 08:08:20'),
(31, '3rd Term', '2023/2024', 'test', 'JSS1', 'Agric Science', '', 'The chemical used to kill the weed is called ___________________', 'chemical', 'pre-emergence', 'post-emergence', 'herbicides', 'herbicides', 'The method that involves using hand, hoe to uproot weed is ', 'Cultural', 'Mechanical', 'emergence', 'smothering', 'mechanical', 'The use of natural enemies like insects to kill weed is _________________ method', 'Chemical', 'Herbicide', 'Biological', 'Systematic', 'Biological', 'Any plant which is not cultivated and is growing where it is not wanted.', 'Weed', 'crop', 'herb', 'vegetable', 'Weed', 'The scientific name for spear grass is called ______________', 'sida acuta', 'tridact', 'Imperata cylindrica', '---------', 'Imperata cylindrica', 'The type of herbicides that destroy plants of a particular plant group is ________________ herbicides', 'non-selective', 'weedicide', 'Insecticides', 'Selective', 'Selective', 'To plant crops in such a way that weeds have very little chance of spreading is called _______________', 'Cultural method', 'Biological method', 'Mechanical method', 'Chemical method', 'Cultural method', 'If you feel ill and uneasy or have body itches or cough and sneeze after using herbicides, go and see a qualified ___________________ immediately', 'Teacher', 'Nurse', 'Doctor', 'Farmer', 'Doctor', 'Herbicides are usually mixed with ______________ before they are applied to plants', 'Water', 'Salt', 'Soap', 'Chemical', 'Water', 'When using chemicals, wear a _______________ mask', 'eyes', 'mouth', 'nose', 'ear', 'nose', '2024-05-23 08:08:20'),
(32, '3rd Term', '2023/2024', 'test', 'JSS1', 'Igbo', '', 'Ihe ndi Igbo ji ezisa ozi oge ochie gunyere ____________', 'Mmiri ', 'oku', 'ite', 'azu ', 'oku', 'Ihe ndi Igbo ji ezisa ozi oge ochie gunyere ____________', 'ewu', 'ite', 'b.Mmiri ', 'mkponaani', 'mkponaani', 'Uzo eji eme ka ozi gbasaa ka a na-akpo _____________', 'Nzisa ozi', 'Abu', 'egwu', 'akwukwo', 'Nzisa ozi', 'N&rsquo;oge ugbua eji ___________ emeka ozi gbasaa', 'Ekwenti', 'abu', 'igba', 'ubo', 'Ekwenti', 'E kere agumagu odinala uzo ___________', 'Ano ', 'abuo', 'iri', 'ato', 'ato', 'Kedu onye bu Azuka __________________', 'Nwanne Obigbo', 'Nwunye Obigbo', 'Nwa Obigbo', 'Odibo Obigbo ', 'Nwunye Obigbo', 'Ihe mere Azuka bu ____________', 'O di ime', 'Onwuru onwu', 'Otara ahuhu', 'O gara oru', 'Onwuru onwu', 'Kedu aha nwanne Azuka ________________', 'Ogonna', 'Ogechi', 'Amaka', 'Chineye', 'Ogechi', 'Chinwe na Amaka nwere agwa ____________', 'Oma', 'Ume', 'Ochicho', 'Ojoo', 'Ojoo', 'Nwannyi ato Anayo choro ilu bu _______________', 'Amaka', 'Chika', 'Nwanneka', 'Chinwe', 'Nwanneka', '2024-05-23 08:08:20'),
(33, '3rd Term', '2023/2024', 'test', 'JSS1', 'History', '', 'Which of the state was a centralized state?', 'Ijaw', 'Ibibio', 'Benin', 'Urhobo', 'Benin', 'Another name for a centralized  state is _______________', 'Self rule', 'Decentralized state', 'Cephalous', 'Autocratic', 'Cephalous', 'The Hausa people traced their origin to _______________', 'Usman', 'Mohammed', 'Buhari', 'Bayajidda', 'Bayajidda', 'The ancestral home of Hausa people is _________________', 'Sokoto', 'Kaduna', 'Daura', 'Maiduguri', 'Daura', 'One of these was not a centralized states in the pre-colonial Nigeria', 'Hausa', 'Tiv', 'Benin', 'Nupe', 'Tiv', 'One of the characteristics of a centralized states in the pre-colonial Nigeria was ________________', 'Building walls round their kingdom', 'Possession of King or Queen', 'Possession of Warrant Officers', 'Possession of titled Chiefs', 'Possession of kings and queens', 'The dominant tribe in the pre-colonial Kanem-Borno were the _________________', 'Hausa', 'Berbers', 'Kanuris', 'Fulanis', 'Kanuris', 'Kanem-Borno empire was founded by _________________ dynasty', 'Safewa', 'Malinke', 'Mande', 'Soninke', 'Safewa', 'The legitimate sons of Bawo were called _______________', 'Hausa banza', 'Illegitimate State', 'Hausa States', 'Hausa Bakwai', 'Hausa Bakwai', 'The children by Bawo&#039;s concubine were called _______________', 'Hausa Banza', 'legitimate sons', 'Hausa Bakwai', 'Hausa Kingdom', 'Hausa Banza', '2024-05-23 08:08:20'),
(34, '3rd Term', '2023/2024', 'test', 'JSS1', 'Security Education', '', 'Primary crime prevention techniques is divided into how many parts', '4', '3', '5', '2', '3', '_______________ means a genuine attempt to reduce and deter crime and criminal activities in the country.', 'Crime prevention', 'Crime management', 'Crime technique', 'Crime method', 'Crime prevention', 'Citizens must report suspicious activities or crimes committed around them to the police force.', 'True', 'False', 'None of the above', 'All of the above', 'True', 'One of the roles of the government in crime prevention is that it actively promotes primary prevention techniques of crime prevention in the country. ', 'False', 'True', 'None of the above', 'All of the above', 'True', 'The technique that focuses on stopping the crimes before it happens is called ____________________', 'Primary prevention', 'tertiary prevention', 'secondary prevention', 'nursery prevention', 'Primary prevention', '____________ and _________ are the different approaches used in crime prevention.', 'The environmental approach and the situational approach', 'The situational approach and the primary approach', 'The environmental approach and the secondary approach', 'None of the above', 'The environmental approach and the situational approach', '8.	______________ seeks to change people typically those at high risks of embarking on a criminal career.', 'Tertiary prevention techniques', 'Secondary prevention techniques', 'Primary prevention techniques', 'None of the above', 'Primary prevention techniques', '____________ and _________ are the different approaches used in crime prevention.', 'The environmental approach and the secondary approach', 'The situational approach and the primary approach', 'The environmental approach and the situational approach', 'None of the above', 'The environmental approach and the situational approach', '____________ refers to the process of applying methods and techniques aimed at reducing and preventing criminal activities in the country.', 'Security management', 'Security intervention', 'Security prevention', 'All of the above', 'Security management', '_____________ techniques focuses on the operation of the criminal justice system and deals with offenders after it has happened. ', 'Tertiary prevention technique', 'Primary prevention technique', 'Secondary	 prevention technique', 'All of the above', 'Tertiary prevention technique', '2024-05-23 08:08:20'),
(35, '3rd Term', '2023/2024', 'test', 'JSS1', 'French Language', '', 'Amadi est chanffeur il conduit un _____________', 'bateam', 'Taxi', 'avion', 'navire', 'Taxi', 'Le pere de mon pere est mon ____________________', 'grand-pere', 'bean-pere', 'cousin', 'oncle', 'grand-pere', 'Un pilote conduit ____________', 'Le bus', 'Le taxi', 'l&#039; avion', 'Le bateam', 'l&#039; avion', 'Un pharmacien produit les _________________', 'medicaments', 'des sacs', 'des regles', 'des foulards', 'medicaments', 'Les conleurs du drapean Nigerian c&#039;est ___________', 'Bleu, blanc et vert', 'vert, blanc et vert', 'ronge, bleu et ronge', 'taune, ronge et bleu', 'vert, blanc et vert', 'Les conleurs dn drapean francais c&#039;est bleu, blanc et ____________', 'vert', 'noir', 'ronge', 'bleu', 'ronge', 'Madame simiri vient du Benin Eiu est donc ______________', 'Beninoise', 'Beninois', 'Togolaise', 'Togo', 'Beninoise', 'Tuillet est le ________________ mois de l&#039; annee', 'Septieme', 'huitieme', 'cinquieme', 'sixieme', 'Septieme', '15 + 30 egale _________________', 'Cinquante', 'Quarante-cinq', 'Quarante-six', 'Quatorze-cinq', 'Quarante-cinq', 'Un medecin travouile a&#039;l&#039; ______________', 'hopital', 'a&#039;la maison', 'a&#039;l&#039; ecole', 'a&#039;l&#039; aeroport', 'hopital', '2024-05-23 08:32:07');
INSERT INTO `questions` (`id`, `term`, `session`, `type`, `class`, `subject`, `instruction`, `q1`, `q1_opt_a`, `q1_opt_b`, `q1_opt_c`, `q1_opt_d`, `q1_answer`, `q2`, `q2_opt_a`, `q2_opt_b`, `q2_opt_c`, `q2_opt_d`, `q2_answer`, `q3`, `q3_opt_a`, `q3_opt_b`, `q3_opt_c`, `q3_opt_d`, `q3_answer`, `q4`, `q4_opt_a`, `q4_opt_b`, `q4_opt_c`, `q4_opt_d`, `q4_answer`, `q5`, `q5_opt_a`, `q5_opt_b`, `q5_opt_c`, `q5_opt_d`, `q5_answer`, `q6`, `q6_opt_a`, `q6_opt_b`, `q6_opt_c`, `q6_opt_d`, `q6_answer`, `q7`, `q7_opt_a`, `q7_opt_b`, `q7_opt_c`, `q7_opt_d`, `q7_answer`, `q8`, `q8_opt_a`, `q8_opt_b`, `q8_opt_c`, `q8_opt_d`, `q8_answer`, `q9`, `q9_opt_a`, `q9_opt_b`, `q9_opt_c`, `q9_opt_d`, `q9_answer`, `q10`, `q10_opt_a`, `q10_opt_b`, `q10_opt_c`, `q10_opt_d`, `q10_answer`, `date`) VALUES
(36, '3rd Term', '2023/2024', 'test', 'JSS1', 'Business Studies', '', 'When a debit entry has a corresponding credit entry, it is called ____________________', 'Contra entry', 'Double entry', 'Single entry', 'Simple entry', 'Double entry', 'Honest means ________________', 'Saying the truth', 'Being punctual', 'Being obedient', 'Dedicated to work', 'Saying the truth', 'The movement of goods from one place to another is _______________', 'Transportation', 'Communication', 'Insurance', 'Labour', 'Transportation', 'The act of representing spoken sounds by signs and character is', 'Consonants', 'Vowel', 'Shorthand', 'account', 'Shorthand', 'The two types of typewriters are __________________ and ___________________', 'Manual and electronic', 'Expensive and Cheap', 'Output and Input device', 'Imperia and Olympia', 'Manual and electronic', 'The left hand side of a ledger account is called', 'Credit side', 'Credit entry', 'Debit side', 'Debiting', 'Debit side', '__________________ is the systematic way of keeping records of business activities', 'Book keeping', 'Account', 'Book record', 'Cash records', 'Book keeping', 'The business that is controlled by two to twenty people is called _________________', 'Sole trade', 'Partnership', 'Limited liability', 'Private business', 'Partnership', 'In book keeping, the abbreviation Dr. stands for', 'Credit', 'Doctor', 'Director', 'Debit', 'Debit', 'The person who types on a computer is called _____________________', 'Typer', 'Secretary', 'Typist', 'Clerk', 'Typist', '2024-05-23 09:17:59'),
(37, '3rd Term', '2023/2024', 'test', 'JSS1', 'HPE', '', 'The state where a person can maintain social interaction with classmates is called ________________', 'mental health', 'personal health', 'social health', 'community health', 'social health', 'These are determinants of health, except ____________', 'physiology', 'healthcare services', 'heredity', 'lifestyle', 'physiology', 'The way and manner of getting rid of solid waste materials is known as _________________', 'refuse disposal', 'sewage disposal', 'refuse', 'dump', 'refuse disposal', '&quot;Father of modern gymnastics&quot; is known ass ____________', 'Mr William Morgan', 'Mr Alexander Ifidon', 'Mr S.I Barrow', 'Mr Friedrich Ludeig John', 'Mr Friedrich Ludeig John', 'Oxygen and _____________ element are found in the water.', 'Iron', 'Phosphorus', 'Hydrogen', 'Sodium', 'Hydrogen', 'Any substance containing one or more nutrients which is taken into the body of an animal for growth is known as ___________', 'Nutrient', 'Composition', 'Food', 'Drugs', 'Food', 'Inadequate protein in the body causes a deficiency disease known as ________________', 'Ricket', 'Ulcer', 'Kwashiorkor', 'Boil', 'Kwashiorkor', 'These are examples of non-contact sports, except _____________', 'Golf', 'Javalin', 'Wrestling', 'Tennis', 'Wrestling', 'Gumnastics are classified into floor activities and _________________ activities.', 'Golf', 'Swimming', 'Dance', 'Apparatus', 'Apparatus', 'The general condition of the body is known as ___________________', 'Physical Educaton', 'Health', 'Social health', 'Nutrition', 'Health', '2024-05-23 09:28:33'),
(38, '3rd Term', '2023/2024', 'test', 'JSS1', 'Basic Technology', '', 'A quick way to draw object without details is called ________________', 'Line', 'Circle', 'Triangle', 'Free hand sketch', 'Free hand sketch', 'One of the following is a material used for freehand sketching', 'Eraser', 'Stencil', 'Protractor', 'Compass', 'Eraser', 'One of the following is a technique for drawing', 'Neat sketch', 'Painting', 'Coloring', 'Shading', 'Neat sketch', 'A narrow part made between two point on a surface is known as _______________', 'Line', 'Angle', 'Circle', 'Triangle', 'Line', 'The first instrument on the board is called ________________', 'Protractor', 'Divider', 'French curve', 'Ruler', 'Ruler', 'The second instrument on the board is called', 'Set-Square', 'Eraser', 'Circle', 'Protractor', 'Protractor', 'The third instrument on the board is called', 'Window', 'Door', 'Drawing board', 'Drawing paper', 'Drawing board', 'The fourth instrument on the board is called', 'Triangle', 'Set-Square', 'Tee-square', 'French curve', 'Set-square', 'In wood work hand tools, the tool for cutting wood is called', 'Scissors', 'razor', 'knife', 'saw', 'saw', 'All of these are types of angle except', 'Obtuse', 'Acute', 'Reflex', 'Object', 'Object', '2024-05-23 09:43:53'),
(39, '3rd Term', '2023/2024', 'test', 'JSS1', 'Civic Education', '', 'One of the symbol or object of national identity in Nigeria includes ________________', 'National flag', 'National Consciousness', 'National unity', 'None of the above', 'National flag', 'Nigeria&#039;s national flag was designed in the year _______________', '1995', '1959', '1955', '1967', '1959', 'Naigeria&#039;s national flag was designed by who?', 'Mr. Michael Taiwo Akinkunmi', 'Chief Obafemi Awolowo', 'Dr. Nnamdi Azikiwe', 'Connel Chukwuemeka Odimegbo Ojukwu', 'Mr. Michael Taiwo Akinkunmi', 'Nigeria is a country that has about 250 ethnic groups with diverse cultural background.', 'True', 'False', 'None of the above', 'All of the above', 'True', 'One of the ways of promoting national unity in Nigeria is called ______________', 'Tolerance', 'Hatred', 'Boosting', 'Fighting', 'Tolerance', 'They are _____________ forms of democracy', 'Three', 'Four', 'Two', 'Five', 'Three', 'The word &quot;Civic&quot; is a _______________ word', 'Greek', 'Yoruba', 'Citizen', 'Latin', 'Greek', 'Which of the following is not a good value _______________', 'Dishonesty', 'Punctuality', 'Obedient', 'Kindness', 'Dishonesty', 'What is the major way a person can acquire citizenship of a country __________________', 'Birth', 'Investigation', 'Force', 'None of the above', 'Birth', 'Skills is a _____________ ability', 'Learnt', 'Moving', 'General', 'None of the above', 'Learnt', '2024-05-24 04:41:49'),
(40, '3rd Term', '2023/2024', 'test', 'JSS1', 'Social Studies', '', 'A group of people who have come together t achieve some goal is called ______________', 'Social group', 'Voluntary organisation', 'Family', 'Club', 'Social group', 'People who have common ancestors are known as ________________', 'Age grade', 'Kinsmen', 'Association', 'Group', 'Kinsmen', 'Voluntary organisations render _____________ services', 'Natural', 'National', 'Special', 'Selfless', 'Selfless', 'Boots, goggles, helmet, hand gloves, nose mark are examples of __________________', 'Saftey', 'Clothes', 'Protective devices', 'Apparatus', 'Protective devices', 'Drivers should not over take other vehicles at a _________________', 'Corner', 'Traffic light', 'Road', 'Pavement', 'Corner', 'The immediate treatment given to an injured or sick person before medical attention is available is known as ______________', 'Medication', 'First aid', 'Drugs', 'Surgery', 'First aid', 'In primary social group , membership is _____________', 'Temporal', 'By choice', 'Mandatory', 'Good', 'Mandatory', 'Extended family is made up of many ______________ families', 'Ancestors', 'Nuclear', 'Compound', 'External', 'Nuclear', 'People that walk along the road are known as ____________________', 'Motorists', 'Cyclists', 'Traffic warden', 'Pedestrians', 'Pedestrians', 'ASUU, NUJ, NUT, NBA are examples of _______________ group', 'Political', 'Pressure', 'School', 'Union', 'Pressure', '2024-05-24 06:25:57'),
(41, '3rd Term', '2023/2024', 'test', 'JSS1', 'Computer Studies', '', 'The process of getting the computer ready for use is called', 'Shut down', 'Booting', 'Switch on', 'Plug in', 'Booting', 'The __________________ booting is the process of restarting the computer ', 'Warm', 'Cold', 'Cooked', 'Lukewarm', 'Cold', 'During _______________ booting, the computer undergoes POST', 'Warm', 'Cold', 'Hot', 'Restart', 'Cold', 'The shortcut for save is ____________', 'Ctrl S', 'Alt S', 'Win S', 'Win R', 'Ctrl S', 'Shutdown means to ______________ the computer', 'On', 'Boot', 'Off', 'research', 'Off`', 'Microsoft word is an example of ______________', 'Word Processor', 'Spreadsheet', 'Database ', 'Internet', 'Word Processor', 'Alt + F4 is used to ___________ a program', 'Open', 'Start', 'Close', 'Type', 'Close', 'ICT means', 'Information Contact Technology', 'Information and Communication Technology', 'Info Command Tech', 'In Communion Teaching', 'Information and Communication Technology', 'Word Processors are used for creating ___________________', 'Document', 'Graphics', 'Internet', 'Media', 'Document', 'Computer resumes Windows in ________________ booting', 'Hot', 'Cold', 'Warm', 'None of the above', 'Warm', '2024-05-24 09:46:30'),
(42, '3rd Term', '2023/2024', 'test', 'JSS1', 'Basic Science', '', '____________ is the complete movement of the earth along its axis for 24 hours.', 'eclipse of the sun', 'Rotation', 'Revolution', 'eclipse of the moon', 'Rotatioin', 'The third planet is called ____________', 'Pluto', 'Jupiter', 'Earth', 'Venus', 'Earth', '________________ causes climate and season of the year', 'Revolution', 'Rotation', 'Sun', 'Moon', 'Revolution', 'Leap year occurs in every _________ ', '1 year', '4 years', '28 years', '4 months', '4 years', '__________ was the name of the dog that was sent to space', 'Laika', 'Sputnik I', 'Edward', 'Soviet', 'Laika', 'The practice of keeping the environment free from dirt and diseases is called ________________', 'Environment', 'Sanitation', 'Exercise', 'Incinerator', 'Sanitation', 'The first woman to enter space is _________________', 'Valentina Tereshkova', 'Buzz Adrin', 'Neil Armstrong', 'Veri', 'Valentina Tereshkova', 'The best sewage disposal is _____________', 'Bush method', 'Water Closet', 'Pit laterine', 'Bucket Laterine', 'Water Closet', 'The first man to set foot on the moon is', 'John Glenn', 'Veri Gagarin', 'Alan Sheoherd', 'Neil Armstrong', 'Neil Armstrong', 'How many planet do we have', '3', '8', '9', '5', '9', '2024-05-24 10:20:13'),
(43, '3rd Term', '2023/2024', 'test', 'JSS1', 'Mathematics', '', 'Find the area of a circle whose radius is 7cm (Take &pi; = 22/7)', '154cm2', '120cm2', '900cm2', '70cm2', '154cm2', 'Calculate the area of the parallelogram whose base is 12cm and height is 1.5cm', '18.0cm2', '15.2cm2', '13.5cm2', '10.2cm2', '18.0cm2', 'Calculate the diameter of a circle whose circumference is 132cm', '11cm', '22cm', '42cm', '60cm', '42cm', 'Which of the following is not a property of a parallelogram', 'All sides are equal in length', 'Each diagonal bisects the parallelogram into two congruent triangle', 'Its opposite sides are equal', 'Its opposite angles are equal', 'All sides are equal in length', 'How many lines of symmetry does an equilateral triangle have', '2', '3', '4', '5', '3', 'The triangle which has NONE of the sides equal to the other side is called _____________ triangle', 'an equilateral', 'a Right angled triangle', 'an Obtuse', 'a Scalene', 'a Scalene', 'How many lines of symmetry has a kite?', '1', '3', '2', '4', '1', 'Calculate the circumference of a circle of radius 7cm.  (Take &pi; = 22/7)', '18cm', '17cm', '42cm', '44cm', '44cm', 'How many edges have a cube?', '10', '8', '12', '4', '12', 'Which of the following is NOT a quadrilateral', 'Circle', 'Rhombus', 'Rectangle', 'Kite', 'Circle', '2024-05-24 10:43:59');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `questions`
--
ALTER TABLE `questions`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `questions`
--
ALTER TABLE `questions`
  MODIFY `id` bigint(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
